/**
 * Curated Chinese name data: characters, surnames and classical relations.
 *
 * Everything here is hand-checked, not scraped. The point of the product is
 * naming taste, so the data is small, structured and explainable:
 *
 *   chars      one entry per character, with tone, a plain-English gloss, a
 *              short image line (used verbatim in explanations), the semantic
 *              fields it belongs to, and where it may be used:
 *                'n'  given name only      'z'  courtesy name (字) only
 *                'nz' both
 *   surnames   common Chinese surnames with a gloss of the character
 *   givenNames the curated list lives in given-names.js
 *   edges      classical relations between a given-name character and a
 *              courtesy-name character:
 *                opposite   反义相对 — the two hold a tension, as in 韩愈/退之
 *                extension  连义引伸 — the second grows out of the first, as in 关羽/云长
 *                allusion   用典       — the second comes from a named source
 *
 * Field vocabulary (keep this list closed — it drives synonym matching):
 *   light dark water mountain sky moon wind tree jade mind virtue peace joy
 *   strength journey words music time clarity depth ease warmth nature stillness
 *
 * Not a translation table and not a database of everyone's name: it is a
 * curated pool, so the same inputs reproduce the same result and every result
 * can be explained. See README.md ("Name data") before extending it.
 *
 * Loaded as a plain script (browser) and via require() (Node checks).
 */
(function (root) {
  'use strict';

  // [han, pinyin, tone, gloss, image, fields, use]
  const chars = [
    // ---- light and its absence -------------------------------------------------
    ['予', 'Yǔ', 3, 'to give', 'the act of handing something over without being asked', 'virtue warmth', 'n'],
    ['嘉', 'Jiā', 1, 'excellent, to commend', 'praise given because it is deserved', 'virtue joy', 'n'],
    ['景', 'Jǐng', 3, 'bright light, to admire', 'what you look up at', 'light mind', 'n'],
    ['白', 'Bái', 2, 'white, plain, clear', 'the colour of a thing with nothing hidden', 'clarity virtue', 'nz'],
    ['羽', 'Yǔ', 3, 'a feather, a wing', 'the light part that makes flight possible', 'sky journey', 'n'],
    ['若', 'Ruò', 4, 'like, as if', 'the word that makes a comparison modest', 'ease nature', 'n'],
    ['河', 'Hé', 2, 'river', 'a broad current under an open sky', 'water journey', 'n'],
    ['昭', 'Zhāo', 1, 'bright, made visible', 'the light that clarifies instead of dazzling', 'light', 'nz'],
    ['明', 'Míng', 2, 'bright, clear', 'light that lets you see a thing as it is', 'light clarity', 'nz'],
    ['朗', 'Lǎng', 3, 'bright and open', 'a sky with nothing between you and the blue', 'light clarity', 'nz'],
    ['曦', 'Xī', 1, 'the morning sun', 'the sun the moment it clears the horizon', 'light', 'n'],
    ['晨', 'Chén', 2, 'dawn', 'the hour when the day has not yet decided', 'light time', 'n'],
    ['晓', 'Xiǎo', 3, 'daybreak, to understand', 'the moment night gives up its argument', 'light time', 'n'],
    ['旭', 'Xù', 4, 'the rising sun', 'light on its way up', 'light', 'n'],
    ['昱', 'Yù', 4, 'sunlight, to shine', 'sunlight falling where someone stands', 'light', 'n'],
    ['晖', 'Huī', 1, 'sunlight', 'borrowed light that still warms', 'light warmth', 'z'],
    ['昕', 'Xīn', 1, 'dawn', 'the first light, brightness at its very beginning', 'light', 'z'],
    ['熹', 'Xī', 1, 'faint first light', 'the smallest light, rising before anyone looks', 'light', 'z'],
    ['曜', 'Yào', 4, 'radiance', 'brightness worn in the open', 'light', 'z'],
    ['皓', 'Hào', 4, 'luminous white', 'the brightness of snow and of white hair', 'light clarity', 'z'],
    ['皎', 'Jiǎo', 3, 'moon-white', 'whiteness that comes from reflected light', 'light moon', 'z'],
    ['光', 'Guāng', 1, 'light', 'what makes a thing visible at all', 'light', 'n'],
    ['晴', 'Qíng', 2, 'clear weather', 'a sky with the argument settled', 'light clarity', 'n'],
    ['亮', 'Liàng', 4, 'bright, resonant', 'brightness you can also hear', 'light', 'n'],
    ['阳', 'Yáng', 2, 'the sun, the bright side', 'the side of a hill that faces the light', 'light warmth', 'n'],
    ['玄', 'Xuán', 2, 'dark and profound', 'black so deep it has something to say', 'dark depth', 'nz'],
    ['晦', 'Huì', 4, 'the dark of the moon', 'the last darkness before dawn, holding its light inward', 'dark', 'z'],
    ['默', 'Mò', 4, 'silent', 'silence kept on purpose', 'stillness dark', 'z'],
    ['隐', 'Yǐn', 3, 'hidden, retired', 'withdrawing so the thing matters more than being seen', 'dark stillness', 'z'],
    ['幽', 'Yōu', 1, 'secluded, dim', 'a place that does not announce itself', 'dark stillness', 'z'],
    // ---- water -----------------------------------------------------------------
    ['清', 'Qīng', 1, 'clear', 'water you can see the bottom of', 'water clarity', 'nz'],
    ['澈', 'Chè', 4, 'limpid, penetrating', 'clarity that goes all the way down', 'water clarity', 'nz'],
    ['澄', 'Chéng', 2, 'settled and clear', 'muddy water left alone until it clears', 'water clarity', 'nz'],
    ['澜', 'Lán', 2, 'a great wave', 'the wave only a wide river can raise', 'water strength', 'nz'],
    ['渊', 'Yuān', 1, 'a deep pool', 'a depth you cannot see but can feel', 'water depth', 'z'],
    ['泉', 'Quán', 2, 'a spring', 'water that keeps arriving from somewhere unseen', 'water nature', 'nz'],
    ['涵', 'Hán', 2, 'to hold, to soak in', 'the capacity to hold what flows through you', 'water depth', 'nz'],
    ['泠', 'Líng', 2, 'the cool ring of water', 'the small clear sound water makes over stone', 'water music', 'z'],
    ['沛', 'Pèi', 4, 'abundant, flowing', 'water with enough to spare', 'water strength', 'z'],
    ['溯', 'Sù', 4, 'to trace upstream', 'going back against the current to find the beginning', 'water mind', 'z'],
    ['润', 'Rùn', 4, 'to moisten, to smooth', 'the rain that makes a hard thing workable', 'water warmth', 'n'],
    ['海', 'Hǎi', 3, 'the sea', 'the place every river agrees to end', 'water depth', 'n'],
    ['江', 'Jiāng', 1, 'a great river', 'water that has already chosen a direction', 'water journey', 'n'],
    ['川', 'Chuān', 1, 'a river, a plain', 'the line water takes across a country', 'water journey', 'nz'],
    ['溪', 'Xī', 1, 'a small stream', 'water small enough to hear', 'water nature', 'n'],
    ['沐', 'Mù', 4, 'to bathe, to be soaked in', 'standing where the light falls', 'water warmth', 'n'],
    ['泽', 'Zé', 2, 'a marsh, a kindness', 'water that stays and feeds what is near it', 'water virtue', 'n'],
    ['湘', 'Xiāng', 1, 'the Xiang river', 'a river with poems written along it', 'water', 'n'],
    ['洛', 'Luò', 4, 'the Luo river', 'the water a capital was built beside', 'water', 'n'],
    ['洲', 'Zhōu', 1, 'an island, a continent', 'land that water has agreed to leave alone', 'water nature', 'n'],
    ['浩', 'Hào', 4, 'vast', 'water too wide to see across', 'water strength', 'n'],
    ['瀚', 'Hàn', 4, 'the vast sea', 'the far edge of the water', 'water strength', 'n'],
    ['霜', 'Shuāng', 1, 'frost', 'cold that arrives quietly and writes on everything', 'water nature', 'z'],
    ['雪', 'Xuě', 3, 'snow', 'the quiet that falls and changes the shape of things', 'water nature', 'n'],
    ['雨', 'Yǔ', 3, 'rain', 'the water nobody has to ask for', 'water nature', 'n'],
    ['露', 'Lù', 4, 'dew', 'water that comes without being called', 'water nature', 'n'],
    ['霁', 'Jì', 4, 'clearing after rain', 'the moment the weather lets go', 'sky clarity', 'z'],
    // ---- mountain and stone ----------------------------------------------------
    ['岳', 'Yuè', 4, 'a great mountain', 'a mountain treated as an ancestor, not an obstacle', 'mountain strength', 'nz'],
    ['嵩', 'Sōng', 1, 'a lofty mountain', 'height that is respected rather than climbed', 'mountain strength', 'z'],
    ['岫', 'Xiù', 4, 'mountain mist, a hollow in a cliff', 'clouds leaving a mountain without being asked', 'mountain sky', 'z'],
    ['壑', 'Hè', 4, 'a ravine', 'the depth a mountain keeps inside itself', 'mountain depth', 'z'],
    ['岚', 'Lán', 2, 'mountain haze', 'the mist that makes a mountain look farther than it is', 'mountain nature', 'nz'],
    ['峰', 'Fēng', 1, 'a peak', 'the part of a mountain that meets the weather first', 'mountain strength', 'n'],
    ['峻', 'Jùn', 4, 'high and steep', 'a slope that asks for respect', 'mountain strength', 'n'],
    ['岩', 'Yán', 2, 'a cliff, rock', 'the part of the hill that will not move', 'mountain strength', 'n'],
    ['屹', 'Yì', 4, 'to stand towering', 'standing where the ground does not shift', 'mountain strength', 'n'],
    ['谷', 'Gǔ', 3, 'a valley', 'the low place that receives everything', 'mountain depth', 'nz'],
    ['砺', 'Lì', 4, 'a whetstone', 'the rough thing that makes another thing sharp', 'mountain mind', 'z'],
    // ---- sky, moon, wind -------------------------------------------------------
    ['霄', 'Xiāo', 1, 'the highest sky', 'the band of sky above the weather', 'sky depth', 'nz'],
    ['苍', 'Cāng', 1, 'deep blue-green, vast', 'the colour of distance', 'sky nature', 'z'],
    ['辰', 'Chén', 2, 'an asterism, a moment in time', 'a star that also means the hour it marks', 'sky time', 'nz'],
    ['望', 'Wàng', 4, 'the full moon, to gaze', 'the moon at its most complete, and the act of looking up', 'moon mind', 'nz'],
    ['宇', 'Yǔ', 3, 'the whole of space', 'the roof that covers everything', 'sky depth', 'n'],
    ['云', 'Yún', 2, 'cloud', 'water that has not yet decided where to fall', 'sky nature', 'n'],
    ['风', 'Fēng', 1, 'wind', 'the thing you notice by what it moves', 'wind journey', 'n'],
    ['飒', 'Sà', 4, 'the sound of wind', 'wind you hear before you feel it', 'wind music', 'z'],
    ['星', 'Xīng', 1, 'a star', 'a light far enough away to be steady', 'sky light', 'n'],
    ['月', 'Yuè', 4, 'the moon', 'the light that keeps returning', 'moon time', 'n'],
    ['朔', 'Shuò', 4, 'a new moon, the north', 'the moon at its darkest and most promising', 'moon time', 'n'],
    ['虹', 'Hóng', 2, 'a rainbow', 'the sky explaining itself after rain', 'sky light', 'n'],
    // ---- trees and growing things ---------------------------------------------
    ['松', 'Sōng', 1, 'pine', 'the tree that does not change its colour in winter', 'tree nature', 'nz'],
    ['柏', 'Bǎi', 3, 'cypress', 'the tree that stays green through the cold', 'tree nature', 'nz'],
    ['竹', 'Zhú', 2, 'bamboo', 'hollow inside, so it bends instead of breaking', 'tree nature', 'nz'],
    ['篁', 'Huáng', 2, 'a bamboo grove', 'bamboo in numbers, a place rather than a stalk', 'tree nature', 'z'],
    ['兰', 'Lán', 2, 'orchid', 'the flower valued for what it does not say', 'tree nature', 'nz'],
    ['蕙', 'Huì', 4, 'orchid', 'a fragrance you notice before you find the flower', 'tree nature', 'z'],
    ['梅', 'Méi', 2, 'plum blossom', 'the flower that opens while it is still cold', 'tree nature', 'n'],
    ['桂', 'Guì', 4, 'cassia, laurel', 'the tree whose scent travels further than its branches', 'tree nature', 'z'],
    ['桐', 'Tóng', 2, 'paulownia', 'the tree grown for what can be made from it', 'tree nature', 'nz'],
    ['枫', 'Fēng', 1, 'maple', 'the tree that shows the season before anyone else', 'tree nature', 'n'],
    ['杉', 'Shān', 1, 'fir', 'a tree that grows straight because it has no choice', 'tree nature', 'n'],
    ['荷', 'Hé', 2, 'lotus', 'the flower that uses mud without becoming it', 'tree nature', 'n'],
    ['莲', 'Lián', 2, 'lotus', 'what grows out of still water', 'tree nature', 'n'],
    ['芷', 'Zhǐ', 3, 'a fragrant herb', 'sweetness growing at the waterline', 'tree nature', 'n'],
    ['薇', 'Wēi', 1, 'a wild fern', 'the green that comes back without being planted', 'tree nature', 'n'],
    ['芸', 'Yún', 2, 'a fragrant herb', 'a small plant with a long memory', 'tree nature', 'n'],
    ['荻', 'Dí', 2, 'reeds', 'grass that stands in water and does not mind', 'tree water', 'n'],
    ['菁', 'Jīng', 1, 'lush, the best part', 'the part of the field worth keeping', 'tree nature', 'n'],
    ['芊', 'Qiān', 1, 'lush grass', 'green with nothing in its way', 'tree nature', 'n'],
    ['苗', 'Miáo', 2, 'a seedling', 'the beginning of something that will be tall', 'tree origin', 'n'],
    ['蔚', 'Wèi', 4, 'lush, flourishing', 'growth dense enough to change a landscape', 'tree strength', 'n'],
    ['茂', 'Mào', 4, 'luxuriant', 'flourishing without needing attention', 'tree strength', 'n'],
    ['荣', 'Róng', 2, 'flourishing, honoured', 'the season when a tree has nothing to prove', 'tree virtue', 'n'],
    // ---- jade and worked stone -------------------------------------------------
    ['璞', 'Pú', 2, 'uncut jade', 'jade still inside its stone, its worth not yet argued for', 'jade origin', 'nz'],
    ['璧', 'Bì', 4, 'a jade disc', 'jade worked into something whole and without a flaw', 'jade strength', 'z'],
    ['珩', 'Héng', 2, 'a jade pendant', 'the jade that sets the rhythm of a belt', 'jade music', 'z'],
    ['瑾', 'Jǐn', 3, 'fine jade', 'the stone that made people build rituals around it', 'jade virtue', 'n'],
    ['瑜', 'Yú', 2, 'fine jade, excellence', 'what is worth keeping after everything is cut away', 'jade virtue', 'n'],
    ['琳', 'Lín', 2, 'fine jade', 'beauty that has to be found first', 'jade strength', 'n'],
    ['瑞', 'Ruì', 4, 'auspicious jade', 'a good sign you can hold', 'jade joy', 'n'],
    ['琢', 'Zhuó', 2, 'to cut and polish jade', 'the work that turns a stone into a decision', 'jade mind', 'n'],
    // ---- mind and virtue -------------------------------------------------------
    ['知', 'Zhī', 1, 'to know', 'knowing the edge of what you know', 'mind clarity', 'nz'],
    ['思', 'Sī', 1, 'to reflect', 'turning a thing over until it shows its other side', 'mind', 'n'],
    ['学', 'Xué', 2, 'to study', 'the habit of being corrected', 'mind words', 'n'],
    ['哲', 'Zhé', 2, 'wise', 'wisdom that can explain itself', 'mind virtue', 'nz'],
    ['智', 'Zhì', 4, 'wisdom', 'knowing which thing to do first', 'mind', 'n'],
    ['敏', 'Mǐn', 3, 'quick-witted', 'quickness in the hands as much as the head', 'mind', 'nz'],
    ['讷', 'Nè', 4, 'slow of speech, deliberate', 'someone who speaks late and is worth waiting for', 'words virtue', 'z'],
    ['慎', 'Shèn', 4, 'careful', 'care taken before the fact, not regret after it', 'mind virtue', 'z'],
    ['笃', 'Dǔ', 3, 'sincere and steady', 'depth that shows as steadiness', 'virtue strength', 'z'],
    ['谦', 'Qiān', 1, 'humble', 'high ground behaving like low ground', 'virtue', 'nz'],
    ['直', 'Zhí', 2, 'upright', 'the shortest line between thinking and saying', 'virtue', 'z'],
    ['诚', 'Chéng', 2, 'sincere', 'words and actions made of the same material', 'virtue warmth', 'nz'],
    ['厚', 'Hòu', 4, 'deep, generous', 'ground thick enough to carry what is built on it', 'virtue depth', 'nz'],
    ['德', 'Dé', 2, 'virtue', 'the part of a person others can rely on', 'virtue', 'n'],
    ['仁', 'Rén', 2, 'humaneness', 'treating another person as a person', 'virtue warmth', 'n'],
    ['礼', 'Lǐ', 3, 'ritual, courtesy', 'the form that lets people be kind without being awkward', 'virtue', 'n'],
    ['善', 'Shàn', 4, 'good', 'the choice made when nobody is watching', 'virtue', 'n'],
    ['修', 'Xiū', 1, 'to cultivate', 'work done on yourself when no one asks for it', 'virtue journey', 'n'],
    ['敬', 'Jìng', 4, 'to respect', 'giving something the weight it actually has', 'virtue', 'n'],
    ['正', 'Zhèng', 4, 'upright, correct', 'a line that does not need to be checked twice', 'virtue clarity', 'n'],
    ['元', 'Yuán', 2, 'origin, the first', 'the beginning everything else is measured from', 'origin time', 'nz'],
    ['恒', 'Héng', 2, 'constant', 'the same on the hundredth day as on the first', 'virtue time', 'nz'],
    ['素', 'Sù', 4, 'plain, undyed silk', 'raw silk before any dye', 'virtue ease', 'nz'],
    ['真', 'Zhēn', 1, 'true', 'the thing itself, before it was improved', 'virtue origin', 'nz'],
    ['朴', 'Pǔ', 3, 'uncarved wood', 'the block before the chisel', 'virtue origin', 'z'],
    ['淳', 'Chún', 2, 'unmixed, honest', 'water with nothing added', 'virtue warmth', 'nz'],
    ['惠', 'Huì', 4, 'kindly, beneficial', 'kindness that leaves the other person better off', 'virtue warmth', 'nz'],
    ['慈', 'Cí', 2, 'compassionate', 'strength that has decided to be gentle', 'virtue warmth', 'n'],
    ['逸', 'Yì', 4, 'unhurried ease', 'pace that looks like leisure because nothing is wasted', 'ease strength', 'nz'],
    ['恬', 'Tián', 2, 'quiet ease', 'a mind with no argument left in it', 'ease stillness', 'z'],
    ['谧', 'Mì', 4, 'stillness', 'quiet so complete it can be heard', 'stillness peace', 'z'],
    ['简', 'Jiǎn', 3, 'simple', 'having removed the parts that were not needed', 'ease clarity', 'nz'],
    ['观', 'Guān', 1, 'to observe', 'watching long enough to see the pattern return', 'mind time', 'z'],
    ['复', 'Fù', 4, 'to return', 'coming back around to where the cycle began', 'time origin', 'z'],
    ['悟', 'Wù', 4, 'to awaken to', 'understanding that arrives all at once after years', 'mind', 'z'],
    ['问', 'Wèn', 4, 'to ask', 'a question kept open instead of answered early', 'mind words', 'z'],
    ['温', 'Wēn', 1, 'gentle warmth', 'warmth without heat', 'warmth virtue', 'nz'],
    ['和', 'Hé', 2, 'harmony', 'different things agreeing without becoming the same', 'peace music', 'nz'],
    ['愉', 'Yú', 2, 'glad', 'pleasure quiet enough to last', 'joy ease', 'z'],
    ['恺', 'Kǎi', 3, 'joyous and kind', 'good cheer that does something useful', 'joy virtue', 'z'],
    ['悦', 'Yuè', 4, 'delight', 'the face that opens when something is good', 'joy warmth', 'nz'],
    ['泊', 'Bó', 2, 'to moor, to stop seeking', 'a boat tied up because it has gone far enough', 'ease stillness', 'z'],
    ['舒', 'Shū', 1, 'to unfold, ease', 'the tight thing loosening', 'ease warmth', 'nz'],
    ['安', 'Ān', 1, 'peace', 'nothing left that needs defending', 'peace ease', 'n'],
    ['宁', 'Níng', 2, 'peace, stillness', 'quiet chosen rather than found', 'peace stillness', 'n'],
    ['晏', 'Yàn', 4, 'calm, late sunlight', 'an evening with nothing urgent in it', 'peace light', 'n'],
    ['澹', 'Dàn', 4, 'still, plain, untroubled', 'still water with no wish to be a wave', 'stillness ease', 'z'],
    ['怡', 'Yí', 2, 'glad, at ease', 'the mood that makes a room easier to be in', 'joy ease', 'n'],
    ['乐', 'Lè', 4, 'joy, music', 'gladness that can be shared', 'joy music', 'n'],
    ['欣', 'Xīn', 1, 'glad', 'the lift in the chest when something goes right', 'joy', 'n'],
    ['陶', 'Táo', 2, 'glad, pottery', 'shaped by hand and fired hard', 'joy ease', 'n'],
    ['悠', 'Yōu', 1, 'leisurely, distant', 'time used at its own speed', 'ease time', 'n'],
    ['畅', 'Chàng', 4, 'smooth, free-flowing', 'no obstruction anywhere along the way', 'ease strength', 'n'],
    ['齐', 'Qí', 2, 'to match, equal', 'measuring yourself against something better', 'virtue mind', 'n'],
    ['亦', 'Yì', 4, 'also, likewise', 'the second thing that belongs with the first', 'ease', 'n'],
    ['树', 'Shù', 4, 'a tree, to establish', 'something planted that outlives the planting', 'tree strength', 'n'],
    ['承', 'Chéng', 2, 'to bear, to inherit', 'carrying what was handed to you, and adding to it', 'strength virtue', 'n'],
    ['轩', 'Xuān', 1, 'a pavilion, a high carriage', 'the high room from which you can see the road', 'ease sky', 'n'],
    ['静', 'Jìng', 4, 'still', 'water at rest, which is when it can reflect', 'stillness peace', 'n'],
    ['姝', 'Shū', 1, 'lovely', 'beauty that does not announce itself', 'warmth', 'n'],
    ['令', 'Lìng', 4, 'fine, good', 'the word used when a thing is well made', 'virtue', 'n'],
    ['仪', 'Yí', 2, 'bearing, ceremony', 'the way a person holds a room without raising a voice', 'virtue ease', 'n'],
    ['然', 'Rán', 2, 'thus, so', 'the word that lets a thing be as it is', 'ease nature', 'n'],
    ['听', 'Tīng', 1, 'to listen', 'attention given before advice', 'stillness mind', 'n'],
    ['抱', 'Bào', 4, 'to embrace', 'holding on to something worth the weight', 'warmth virtue', 'n'],
    ['一', 'Yī', 1, 'one', 'the number everything else is built out of', 'origin stillness', 'n'],
    ['有', 'Yǒu', 3, 'to have', 'having enough to give some away', 'virtue', 'n'],
    ['容', 'Róng', 2, 'to contain, to allow', 'room inside for someone else', 'depth virtue', 'n'],
    ['山', 'Shān', 1, 'mountain', 'the ground standing up', 'mountain nature', 'n'],
    ['念', 'Niàn', 4, 'to think of, to hold in mind', 'keeping someone in mind without being asked', 'mind warmth', 'n'],
    ['青', 'Qīng', 1, 'green, young', 'the colour of things still growing', 'nature time', 'n'],
    ['禾', 'Hé', 2, 'standing grain', 'the field in the weeks before harvest', 'nature', 'n'],
    ['归', 'Guī', 1, 'to return', 'going back to the place that still knows you', 'journey origin', 'n'],
    ['怀', 'Huái', 2, 'to hold in the heart', 'carrying someone with you without effort', 'warmth mind', 'n'],
    ['如', 'Rú', 2, 'like, as', 'the word that makes a comparison gentle', 'ease', 'n'],
    ['初', 'Chū', 1, 'the beginning', 'the first attempt, before habits form', 'origin time', 'n'],
    ['非', 'Fēi', 1, 'not, to correct', 'the honesty of naming your own mistake', 'mind virtue', 'n'],
    ['微', 'Wēi', 1, 'subtle, minute', 'the detail that decides everything', 'mind depth', 'n'],
    ['心', 'Xīn', 1, 'heart, mind', 'the part that decides before the argument starts', 'mind warmth', 'n'],
    ['文', 'Wén', 2, 'writing, culture', 'the marks people leave so others can follow', 'words virtue', 'n'],
    ['书', 'Shū', 1, 'book, writing', 'thought made portable', 'words mind', 'nz'],
    ['言', 'Yán', 2, 'words', 'the thing you are answerable for once it is out', 'words', 'nz'],
    ['墨', 'Mò', 4, 'ink', 'the material that makes thought visible', 'words depth', 'nz'],
    ['砚', 'Yàn', 4, 'an inkstone', 'the stone that holds what you grind yourself', 'words mountain', 'nz'],
    ['笺', 'Jiān', 1, 'fine note paper', 'small paper for the few words that matter', 'words ease', 'z'],
    ['诗', 'Shī', 1, 'poetry', 'language arranged until it is worth remembering', 'words mind', 'n'],
    ['歌', 'Gē', 1, 'song', 'words that needed a tune to be true', 'music joy', 'n'],
    ['琴', 'Qín', 2, 'the qin zither', 'an instrument that rewards a quiet room', 'music ease', 'n'],
    ['笛', 'Dí', 2, 'flute', 'a sound that carries across a valley', 'music nature', 'n'],
    ['弦', 'Xián', 2, 'a string', 'tension that exists in order to sing', 'music strength', 'z'],
    ['律', 'Lǜ', 4, 'pitch, law', 'the order that turns a sound into music', 'music virtue', 'nz'],
    ['韶', 'Sháo', 2, 'the music of Shun', 'music said to have delayed a meal', 'music joy', 'z'],
    ['时', 'Shí', 2, 'time, season', 'the season that arrives whether you are ready or not', 'time', 'z'],
    ['秋', 'Qiū', 1, 'autumn', 'the season that teaches letting go', 'time nature', 'n'],
    ['春', 'Chūn', 1, 'spring', 'the season that starts without permission', 'time nature', 'n'],
    ['冬', 'Dōng', 1, 'winter', 'the season that asks what you kept', 'time nature', 'n'],
    ['夏', 'Xià', 4, 'summer', 'the season at full volume', 'time nature', 'n'],
    ['原', 'Yuán', 2, 'a plain, a source', 'open ground where a thing can be seen from far off', 'nature origin', 'n'],
    // ---- journey ---------------------------------------------------------------
    ['远', 'Yuǎn', 3, 'far', 'the road that keeps going past the horizon', 'journey depth', 'nz'],
    ['遐', 'Xiá', 2, 'far, distant', 'distance kept on purpose', 'journey depth', 'z'],
    ['航', 'Háng', 2, 'to sail', 'choosing a direction and holding it', 'journey water', 'n'],
    ['舟', 'Zhōu', 1, 'a boat', 'the small thing you cross something large in', 'journey water', 'nz'],
    ['帆', 'Fān', 1, 'a sail', 'the part of the journey that is not rowing', 'journey wind', 'z'],
    ['履', 'Lǚ', 3, 'to tread', 'the ground you actually walk on', 'journey virtue', 'z'],
    ['苇', 'Wěi', 3, 'a reed', 'a reed thin enough to cross a river on', 'journey nature', 'z'],
    ['越', 'Yuè', 4, 'to surpass, to cross over', 'going past the mark that was set for you', 'journey strength', 'n'],
    ['行', 'Xíng', 2, 'to walk, conduct', 'the name is what you are called; this is what you do', 'journey virtue', 'n'],
    ['游', 'Yóu', 2, 'to wander', 'moving without needing to arrive', 'journey ease', 'n'],
    ['渡', 'Dù', 4, 'to cross', 'the water between here and the other side', 'journey water', 'n'],
    ['骏', 'Jùn', 4, 'a fine horse', 'speed with good judgement behind it', 'strength journey', 'n'],
    ['鸿', 'Hóng', 2, 'the swan goose', 'a bird that crosses the whole sky', 'strength journey', 'nz'],
    ['鹤', 'Hè', 4, 'crane', 'the long-lived bird that stands in the shallows', 'strength nature', 'z'],
    ['鸢', 'Yuān', 1, 'a kite, a hawk', 'flight at the top of the sky', 'strength sky', 'z'],
    ['铮', 'Zhēng', 1, 'the ring of metal', 'the note a good blade makes', 'strength music', 'n'],
    ['擎', 'Qíng', 2, 'to hold up', 'taking the weight so someone else does not', 'strength', 'n'],
    ['飞', 'Fēi', 1, 'to fly', 'motion released from the ground', 'journey sky', 'n'],
    ['盈', 'Yíng', 2, 'full, flourishing', 'fullness that still has room to grow', 'joy nature', 'n'],
    ['虚', 'Xū', 1, 'empty, open', 'space left open for another possibility', 'depth ease', 'z'],
    ['瓢', 'Piáo', 2, 'a gourd dipper', 'a small vessel that makes enough feel enough', 'ease nature', 'z'],
    ['水', 'Shuǐ', 3, 'water', 'the element that finds the lowest place', 'water ease', 'z'],
    ['玉', 'Yù', 4, 'jade', 'warmth and hardness held in one material', 'jade virtue', 'z'],
    ['易', 'Yì', 4, 'simple, changing', 'the change that makes a rule usable', 'clarity time', 'z'],
    ['卓', 'Zhuó', 2, 'outstanding', 'standing above the line everyone else accepted', 'strength', 'n'],
    ['毅', 'Yì', 4, 'resolute', 'the decision that survives a bad week', 'strength virtue', 'n'],
    ['勇', 'Yǒng', 3, 'courage', 'fear that has been given a job', 'strength', 'n']
  ].map(([han, pinyin, tone, gloss, image, fields, use]) => ({ han, pinyin, tone, gloss, image, fields: fields.split(' '), use }));

  // [han, pinyin, tone, meaning]
  const surnames = [
    ['林', 'Lín', 2, 'forest'],
    ['周', 'Zhōu', 1, 'all around, complete'],
    ['沈', 'Shěn', 3, 'deep'],
    ['许', 'Xǔ', 3, 'to allow, to promise'],
    ['陆', 'Lù', 4, 'land'],
    ['顾', 'Gù', 4, 'to care for, to look after'],
    ['陈', 'Chén', 2, 'to lay out, to display'],
    ['苏', 'Sū', 1, 'to revive'],
    ['叶', 'Yè', 4, 'leaf'],
    ['江', 'Jiāng', 1, 'a great river'],
    ['温', 'Wēn', 1, 'gentle, warm'],
    ['白', 'Bái', 2, 'white, plain'],
    ['秦', 'Qín', 2, 'an ancient state, used as a surname'],
    ['唐', 'Táng', 2, 'the Tang dynasty, used as a surname'],
    ['程', 'Chéng', 2, 'a measure, a stage of a journey'],
    ['何', 'Hé', 2, 'what, how'],
    ['罗', 'Luó', 2, 'a net, to gather'],
    ['高', 'Gāo', 1, 'high'],
    ['崔', 'Cuī', 1, 'towering'],
    ['谢', 'Xiè', 4, 'to thank'],
    ['韩', 'Hán', 2, 'an ancient state, used as a surname'],
    ['石', 'Shí', 2, 'stone'],
    ['田', 'Tián', 2, 'a field'],
    ['邵', 'Shào', 4, 'a place name, used as a surname'],
    ['赵', 'Zhào', 4, 'an ancient state, used as a surname'],
    ['孟', 'Mèng', 4, 'eldest, first'],
    ['季', 'Jì', 4, 'youngest'],
    ['傅', 'Fù', 4, 'to instruct'],
    ['卢', 'Lú', 2, 'an ancient state, used as a surname'],
    ['董', 'Dǒng', 3, 'to supervise'],
    ['谭', 'Tán', 2, 'to talk'],
    ['乔', 'Qiáo', 2, 'tall, lofty'],
    ['段', 'Duàn', 4, 'a section, a stage'],
    ['严', 'Yán', 2, 'strict, dignified'],
    ['钟', 'Zhōng', 1, 'a bell'],
    ['方', 'Fāng', 1, 'square, direction'],
    ['雷', 'Léi', 2, 'thunder'],
    ['洪', 'Hóng', 2, 'vast, a flood'],
    ['宁', 'Níng', 2, 'peaceful'],
    ['卫', 'Wèi', 4, 'to guard'],
    ['戴', 'Dài', 4, 'to wear, to honour'],
    ['章', 'Zhāng', 1, 'a chapter, a seal'],
    ['华', 'Huà', 4, 'splendid'],
    ['金', 'Jīn', 1, 'gold, metal'],
    ['魏', 'Wèi', 4, 'an ancient state, used as a surname'],
    ['陶', 'Táo', 2, 'pottery, glad'],
    ['姜', 'Jiāng', 1, 'ginger, an ancient surname'],
    ['范', 'Fàn', 4, 'a model, a pattern'],
    ['彭', 'Péng', 2, 'drumbeats, an ancient surname'],
    ['曾', 'Zēng', 1, 'formerly, an ancient surname'],
    ['吕', 'Lǚ', 3, 'a musical pitch, an ancient surname'],
    ['丁', 'Dīng', 1, 'a grown man, a fourth heavenly stem'],
    ['任', 'Rèn', 4, 'to bear, an office'],
    ['姚', 'Yáo', 2, 'an ancient surname'],
    ['袁', 'Yuán', 2, 'an ancient surname'],
    ['廖', 'Liào', 4, 'an ancient surname'],
    ['邹', 'Zōu', 1, 'an ancient state, used as a surname'],
    ['熊', 'Xióng', 2, 'bear'],
    ['孔', 'Kǒng', 3, 'a hole, the surname of Confucius'],
    ['康', 'Kāng', 1, 'health, ease'],
    ['毛', 'Máo', 2, 'hair, a feather'],
    ['邱', 'Qiū', 1, 'a variant of 丘, a hill'],
    ['夏', 'Xià', 4, 'summer, a dynasty'],
    ['侯', 'Hóu', 2, 'a marquis'],
    ['龙', 'Lóng', 2, 'dragon'],
    ['万', 'Wàn', 4, 'ten thousand'],
    ['赖', 'Lài', 4, 'to rely on'],
    ['龚', 'Gōng', 1, 'to offer respectfully'],
    ['文', 'Wén', 2, 'writing, culture'],
    ['舒', 'Shū', 1, 'to unfold, ease'],
    ['楚', 'Chǔ', 3, 'clear, an ancient state'],
    ['毕', 'Bì', 4, 'to finish'],
    ['齐', 'Qí', 2, 'an ancient state, used as a surname'],
    ['项', 'Xiàng', 4, 'the back of the neck, an ancient state'],
    ['梅', 'Méi', 2, 'plum blossom'],
    ['柯', 'Kē', 1, 'a branch, an axe handle'],
    ['童', 'Tóng', 2, 'a child'],
    ['池', 'Chí', 2, 'a pond'],
    ['费', 'Fèi', 4, 'to spend, an ancient surname'],
    ['路', 'Lù', 4, 'a road'],
    ['岳', 'Yuè', 4, 'a great mountain'],
    ['闵', 'Mǐn', 3, 'an ancient state, used as a surname'],
    ['蒲', 'Pú', 2, 'cattail, rushes'],
    ['习', 'Xí', 2, 'to practise'],
    ['苗', 'Miáo', 2, 'a seedling'],
    ['穆', 'Mù', 4, 'solemn, gentle'],
    ['阮', 'Ruǎn', 3, 'an ancient state, used as a surname'],
    ['尤', 'Yóu', 2, 'especially, outstanding'],
    ['骆', 'Luò', 4, 'a white horse with a black mane'],
    ['纪', 'Jì', 4, 'a record, a reign'],
    ['师', 'Shī', 1, 'a teacher']
  ].map(([han, pinyin, tone, meaning]) => ({ han, pinyin, tone, meaning }));

  // Classical relations. `from` is a character that appears in a given name,
  // `to` is a character that can serve in a courtesy name.
  // [from, to, note]
  const opposite = [
    ['明', '晦', 'the given name carries the light; the courtesy name keeps it inward, which is why 朱熹 took 元晦 against 熹'],
    ['白', '晦', 'a name that says plainly what it is, paired with the dark that gives plainness its depth'],
    ['昭', '隐', 'brightness that chooses not to be shown — the same tension 韩愈 built with 愈 and 退之'],
    ['敏', '讷', 'quickness answered by slowness of speech: 君子欲讷于言而敏于行'],
    ['言', '讷', 'words held back so that the ones that come out are worth hearing'],
    ['航', '泊', 'the name sets out; the courtesy name is the harbour it agrees to come back to'],
    ['蔚', '素', 'abundance paired with plainness, so that the growth does not become noise'],
    ['修', '逸', 'effort on one side, unhurried ease on the other — neither works alone'],
    ['承', '逸', 'bearing weight without looking strained is the whole craft of it'],
    ['乐', '澹', 'gladness that has been made quiet enough to keep'],
    ['星', '隐', 'a steady light that does not need to be looked at to keep shining']
  ];
  const extension = [
    ['明', '昕', 'the given name says bright; the courtesy name says where brightness begins'],
    ['明', '曜', 'light becomes radiance once it stops hiding'],
    ['清', '澄', 'clear water settles into something you can see through'],
    ['澈', '澄', 'clarity that goes all the way down ends in stillness'],
    ['知', '哲', 'knowing grows into wisdom once it can explain itself'],
    ['知', '问', 'knowing begins with a question kept open'],
    ['思', '悟', 'reflection matures into the moment things fall into place'],
    ['思', '笃', 'thinking well is only half; the other half is what 中庸 calls 笃行'],
    ['修', '笃', 'cultivation shows up as steadiness or it did not happen'],
    ['景', '岳', 'the name comes from 高山仰止，景行行止 — so the courtesy name climbs'],
    ['远', '遐', 'distance extended past the point where the name began'],
    ['川', '澜', 'a river only becomes waves once it has gathered enough of itself'],
    ['山', '壑', 'a mountain is measured by what it hides inside'],
    ['松', '柏', '松 joined by 柏: the two trees that do not surrender to winter'],
    ['云', '岫', 'a cloud is only visible once it leaves the mountain'],
    ['月', '望', 'the moon at the point where it is finally full'],
    ['星', '辰', 'one star becomes the marker by which a season is counted'],
    ['雪', '霁', 'snow ends in clearing; the quiet is only half the story'],
    ['砚', '墨', 'the inkstone exists for the ink, and the ink for the words'],
    ['书', '笺', 'a book starts as a few sheets of paper and a decision'],
    ['言', '简', 'good words end up few'],
    ['乐', '愉', 'shared gladness settles into something you can live on'],
    ['安', '恬', 'peace becomes ease once nothing is left to defend'],
    ['宁', '谧', 'stillness deepens until it can be heard'],
    ['静', '谧', 'a still surface and a quiet depth are the same discipline'],
    ['嘉', '谦', 'excellence that has learned to sit lower than it could'],
    ['予', '和', 'giving freely is how a room ends up in harmony'],
    ['望', '遐', 'gazing outward is the beginning of a long road'],
    ['元', '复', 'what begins in an origin returns to it'],
    ['真', '朴', 'truth, when it is not decorated, looks like uncarved wood'],
    ['素', '璞', 'plain silk and unworked jade: the same refusal to be improved'],
    ['墨', '砚', 'ink needs a stone to hold it, or the thought runs away'],
    ['盈', '复', 'fullness and return are one cycle'],
    ['禾', '原', 'grain only grows where the ground is open'],
    ['川', '舟', 'a river implies a boat, and a boat implies a crossing'],
    ['航', '帆', 'sailing is mostly waiting for the wind to agree'],
    ['心', '悟', 'the heart understands before the argument finishes'],
    ['容', '厚', 'having room for others is what depth looks like from outside'],
    ['恒', '复', 'constancy is the same return, made by choice'],
    ['青', '蔚', 'the colour of things still growing becomes a whole landscape']
  ];
  // [from, to, source, note]
  const allusion = [
    ['明', '昭', '《诗经·大雅·既醉》"昭明有融"', 'the courtesy name is lifted from a line of the Classic of Poetry where the light is broad and lasting'],
    ['知', '默', '《道德经》"知者不言，言者不知"', 'knowing at its most complete stops explaining itself'],
    ['知', '白', '《道德经》"知其白，守其黑"', 'the name knows what is bright; the courtesy name is the plainness it keeps'],
    ['思', '笃', '《中庸》"博学之，审问之，慎思之，明辨之，笃行之"', 'the courtesy name takes the last of the five steps: reflection that turns into practice'],
    ['修', '远', '《离骚》"路漫漫其修远兮，吾将上下而求索"', 'the road is long, and the work on oneself is what the road is made of'],
    ['松', '柏', '《论语·子罕》"岁寒，然后知松柏之后凋也"', 'only the cold reveals which tree was serious'],
    ['月', '望', '李白《静夜思》"举头望明月"', 'looking up at the moon is the oldest Chinese gesture of missing someone'],
    ['云', '岫', '陶渊明《归去来兮辞》"云无心以出岫"', 'clouds leave the mountain without intending to — the courtesy name is that unhurried exit'],
    ['一', '素', '《道德经》"见素抱朴"', 'the courtesy name is the undyed silk: the same phrase the given name already half-quotes'],
    ['白', '真', '《道德经》"见素抱朴，少私寡欲"', 'plainness taken as far as it will go'],
    ['观', '复', '《道德经》"万物并作，吾以观复"', 'watch everything grow, and see it all come back around'],
    ['谷', '虚', '《道德经》"旷兮其若谷"', 'the wide-open emptiness a valley demonstrates'],
    ['飞', '鸢', '《诗经·大雅·旱麓》"鸢飞戾天，鱼跃于渊"', 'the hawk reaches the sky, the fish reaches the pool: each goes as far as it can'],
    ['渊', '鸢', '《诗经·大雅·旱麓》"鸢飞戾天，鱼跃于渊"', 'depth and height given as equals in one line'],
    ['温', '玉', '《诗经·秦风·小戎》"言念君子，温其如玉"', 'warmth with the hardness of jade is the old ideal of a decent person'],
    ['元', '善', '《周易·乾》"元者，善之长也"', 'the first of the four virtues is where goodness begins'],
    ['恒', '时', '《论语·子路》"人而无恒，不可以作巫医"', 'without constancy nothing else can be trusted'],
    ['简', '易', '《周易·系辞上》"易简而天下之理得矣"', 'simplicity is not the absence of rigour; it is the result of it'],
    ['厚', '德', '《周易·坤》"地势坤，君子以厚德载物"', 'the ground carries everything, which is what generosity actually is'],
    ['书', '悟', '王羲之《兰亭集序》"悟言一室之内"', 'friends talking a thing through in one small room'],
    ['竹', '惠', '王羲之《兰亭集序》"惠风和畅"', 'bamboo and a kindly breeze, from the same afternoon the essay describes'],
    ['山', '岳', '杜甫《望岳》"会当凌绝顶，一览众山小"', 'the smallness of everything else once you reach the top'],
    ['月', '泉', '王维《山居秋暝》"明月松间照，清泉石上流"', 'the moon above, the spring below — the poem the courtesy name borrows from'],
    ['雪', '梅', '卢梅坡《雪梅》"梅须逊雪三分白，雪却输梅一段香"', 'snow wins on whiteness, the plum wins on scent; neither wins outright'],
    ['乐', '山', '《论语·雍也》"知者乐水，仁者乐山"', 'the wise delight in water, the good in mountains — the courtesy name declares which one'],
    ['乐', '水', '《论语·雍也》"知者乐水，仁者乐山"', 'the same line, the other half of the pair'],
    ['一', '瓢', '《论语·雍也》"一箪食，一瓢饮，在陋巷"', 'a single gourd of water was enough for the disciple Confucius praised most'],
    ['心', '远', '陶渊明《饮酒》"心远地自偏"', 'a mind that has gone elsewhere makes even a busy street remote'],
    ['春', '晓', '孟浩然《春晓》"春眠不觉晓"', 'the poem everybody in China can still recite in spring'],
    ['江', '雪', '柳宗元《江雪》"孤舟蓑笠翁，独钓寒江雪"', 'the loneliness in the poem is chosen, not suffered'],
    ['竹', '静', '《道德经》"致虚极，守静笃"', 'emptiness taken to its limit, stillness held firmly'],
    ['松', '风', '王维《山居秋暝》"明月松间照"', 'the wind in the pines is the sound that afternoon left behind'],
    ['兰', '蕙', '《楚辞·九歌》"蕙肴蒸兮兰藉"', 'the two orchids the Chu songs keep returning to'],
    ['知', '微', '《周易·系辞下》"知微知彰"', 'seeing the small sign before it becomes the large event'],
    ['学', '时', '《论语·学而》"学而时习之，不亦说乎"', 'the first line of the Analects: learning, and going over it again'],
    ['诗', '礼', '《论语·季氏》"不学诗，无以言；不学礼，无以立"', 'without the poems there is nothing to say; without the rites nowhere to stand'],
    ['非', '知', '《淮南子·原道训》"蘧伯玉年五十而有四十九年非"', 'at fifty he could see the mistakes of the previous forty-nine years'],
    ['齐', '思', '《论语·里仁》"见贤思齐焉"', 'meeting someone better is the beginning of becoming better'],
    ['望', '岳', '杜甫《望岳》"会当凌绝顶，一览众山小"', 'gazing at the great mountain is already the first step up'],
    ['鹤', '云', '刘禹锡《秋词》"晴空一鹤排云上，便引诗情到碧霄"', 'one crane pushing through cloud takes the whole poem with it'],
    ['山', '渊', '《诗经·大雅·旱麓》"鸢飞戾天，鱼跃于渊"', 'the line that makes height and depth two halves of one sentence']
  ];

  const api = { chars, surnames, opposite, extension, allusion };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.HanziNameData = api;
})(typeof window === 'undefined' ? globalThis : window);
